[edge]
bastion ansible_host=34.143.201.113

[management]
gitlab ansible_host=10.0.3.2
sast ansible_host=10.0.3.3

[workload]
master ansible_host=10.0.2.2
worker ansible_host=10.0.2.3

[private:children]
management
workload

[all:vars]
ansible_user=usr_23521746_gm_uit_edu_vn
ansible_ssh_private_key_file=/home/tung/.ssh/google_compute_engine
ansible_ssh_common_args=-o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=30 -o ConnectionAttempts=6
ansible_python_interpreter=/usr/bin/python3.10

[private:vars]
ansible_ssh_common_args=-o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=30 -o ConnectionAttempts=6 -o ProxyCommand="ssh -i /home/tung/.ssh/google_compute_engine -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=30 -o ConnectionAttempts=6 -W %h:%p usr_23521746_gm_uit_edu_vn@34.143.201.113"
