#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/harbor
- name: Install Docker dependencies
  apt:
    name:
      [apt-transport-https, ca-certificates, curl, software-properties-common]
    state: present

- name: Install Docker and Docker Compose V2
  apt:
    name: [docker.io, docker-compose-v2]
    state: present
    update_cache: yes

- name: Download Harbor installer archive
  get_url:
    url: https://github.com/goharbor/harbor/releases/download/v2.10.0/harbor-offline-installer-v2.10.0.tgz
    dest: /tmp/harbor-installer.tgz

- name: Create Harbor directory
  file:
    path: /opt/harbor
    state: directory

- name: Extract Harbor installer
  unarchive:
    src: /tmp/harbor-installer.tgz
    dest: /opt/harbor
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Configure harbor.yml from template
  shell: |
    cd /opt/harbor
    cp harbor.yml.tmpl harbor.yml
    sed -i 's/hostname: reg.mydomain.com/hostname: 10.0.2.20/g' harbor.yml
    # Tạm thời tắt https vì ta bọc Nginx ngoài Bastion rồi
    sed -i 's/https:/#https:/g' harbor.yml
    sed -i 's/  port: 443/#  port: 443/g' harbor.yml
  args:
    creates: /opt/harbor/harbor.yml

- name: Run Harbor installation script
  shell: ./install.sh
  args:
    chdir: /opt/harbor
    creates: /lib/systemd/system/harbor.service # Hoặc chạy qua docker-compose up -d ngầm
