#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/bastion_nginx
- name: Install Nginx on Bastion
  apt:
    name: nginx
    state: present
    update_cache: yes
  notify: Restart Nginx

- name: Create Nginx reverse proxy config for DevSecOps tools
  copy:
    dest: /etc/nginx/sites-available/devsecops-proxy.conf
    content: |
      # Điều hướng đến GitLab
      server {
          listen 80;
          server_name gitlab.local;
          location / {
            proxy_pass "http://{{ hostvars['gitlab'].ansible_host }}:80";
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
          }
      }
  notify: Restart Nginx

- name: Enable config by creating symlink
  file:
    src: /etc/nginx/sites-available/devsecops-proxy.conf
    dest: /etc/nginx/sites-enabled/devsecops-proxy.conf
    state: link
  notify: Restart Nginx

- name: Remove default Nginx config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart Nginx