#SPDX-License-Identifier: MIT-0
# tasks file for roles/k3s_worker
- name: Install curl
  ansible.builtin.apt:
    name: curl
    state: present
    update_cache: yes

- name: Install K3s agent and join cluster
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | K3S_URL="https://{{ hostvars['k3s_master']['ansible_host'] }}:6443" K3S_TOKEN="{{ hostvars['K3S_TOKEN_HOLDER']['token'] }}" sh -
  args:
    creates: /etc/systemd/system/k3s-agent.service
