---
# defaults file for envoy
envoy_image: envoyproxy/envoy:v1.31-latest
envoy_container_name: envoy
envoy_host_http_port: 80
envoy_listen_port: 8080
envoy_admin_port: 9901
envoy_upstream_host: "{{ hostvars['gitlab'].ansible_host }}"
envoy_upstream_port: 80
envoy_config_path: /etc/envoy/envoy.yaml
envoy_wasm_path: "{{ coraza_wasm_path }}"
envoy_wasm_vm_id: coraza-filter-vm
envoy_wasm_filter_name: coraza-filter
envoy_wasm_configuration: |
  {
    "directives_map": {
      "default": [
        "Include @demo-conf",
        "SecDebugLogLevel 9",
        "SecRuleEngine On",
        "Include @crs-setup-conf",
        "Include @owasp_crs/*.conf"
      ]
    },
    "default_directives": "default"
  }
